
name: Build PR

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [16]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Patch Brilliant
      run: |
        git config --global user.email "no-reply@github.com"
        git config --global user.name "Github Actions"
        ./gradlew applyPatches
    - name: Build Brilliant Paperclip
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        ./gradlew paperclip
    - uses: actions/upload-artifact@v2
      with:
        name: Brilliant-Branch${{ github.event.pull_request.number }}-JDK${{ matrix.java }}
        path: brilliant.jar
